### ISSUE TITLE
Calculate Battle outcome

### ISSUE THREAD

**Issue by florian-kohrs** [flofe104/elmlord#11]
- [x] Algorithm (Paper)

- [x] Calculate Screen (UI)

- [x] Implementation algorithm

- [x] Combine UI with algorithm

- [x]  Terrain bonus + Auflösung

- [x] Connect Map with battle system

- [x] Defense castle boni

- [x] Siege Battles

- [x] Terrain bonus

- [x] Reset player to castle if he lost the battle if not the castle siege

- [x] After a siege the winner takes the settlement

**Comment by SerQuicky** [comment]
The terrain bonus is implemented, now I just need the terrain of the `MapTile` where the player is standing on. Please replace this line `generateActionOverview bS Map.Grass` in `BattleTemplate` with something like `generateActionOverview (mygreatfunc bS.player.entity)`.

**Comment by SerQuicky** [comment]
When a player can move to another player, add the action in the action menu, so they can battle if they stay on the same tile.
