### ISSUE TITLE
Implement UI and Logik for Settlement Interactions

### ISSUE THREAD

**Issue by florian-kohrs** [flofe104/elmlord#6]
- [x] Recruit Troops

- [x] Stationing troops

- [x] Stats overview

- [x] Settlement overview

- [x] Building-Part (Combine with real logic)

**Comment by SerQuicky** [comment]
I have created a new `Msg` with the name `SettlementMsg`, it can be found under `Types`.
This `Msg-Type` contains all interactions/action with the settlement modal. In `Main.elm` the `Msg-Type` is used in the function `updateSettlement`. Now we just have to combine the `Model` with action.

**Example: Buy Troops**

- Add 10 units from a `troopType`

- Subtract `X Gold` from the player
