### ISSUE TITLE
Refactoring of the base game version

### ISSUE THREAD

**Issue by SerQuicky** [flofe104/elmlord#9]
Code-Refactoring of the base game version

- [x] Check usefulness of  `OperatorExt` module (mapFilter)
- [x] Replace Troop list from wordEntity with Dictionary TroopType Int
- [x] Check Responsive Design
- [x] Prettify the UI
- [x] Comment all classes
- [x] Restructure the files and folders
- [x] Gamestate refactoring
- [x] CSS Refactoring

**Comment by flofe104** [comment]
- [ ] Replace `LordList` with `NEList`
- [ ] Check usefulness of  `OperatorExt` module
